import configparser

config = configparser.ConfigParser()

config.read("config.ini")

OPENAI_API_KEY = config["AZURE_LANGCHAIN_OPENAI"]["AZURE_OPENAI_API_KEY"]
AZURE_ENDPOINT = config["AZURE_LANGCHAIN_OPENAI"]["AZURE_OPENAI_ENDPOINT"]
AZURE_DEPLOYMENT_NAME = config["AZURE_LANGCHAIN_OPENAI"]["AZURE_DEPLOYMENT_NAME"]


AZURE_EMBEDDING_DEPLOYMENT_NAME = config["EMBEDDINGS"][
    "AZURE_EMBEDDING_DEPLOYMENT_NAME"
]
